export interface ThemeColors {
  background: string
  card: string
  inputBackground: string
  textPrimary: string
  textSecondary: string
  textMuted: string
  textDetail: string
  border: string
  borderLight: string
  chevron: string
  primary: string
  primaryText: string
  onPrimaryText: string
  success: string
  error: string
  warning: string
  classSundaySchool: string
  classSmallGroup: string
  classFNA: string
  classBibleStudy: string
  alertWarningBg: string
  alertWarningBorder: string
  alertInfoBg: string
  alertInfoBorder: string
  alertSuccessBg: string
  alertSuccessText: string
  alertDangerBg: string
  alertDangerText: string
  alertOrangeBg: string
  alertOrangeText: string
  tabBarBackground: string
  tabBarActiveTint: string
  tabBarInactiveTint: string
  tabBarBorder: string
}

export const lightColors: ThemeColors = {
  background: '#f8f9fa',
  card: '#fff',
  inputBackground: '#F5F5F5',
  textPrimary: '#333',
  textSecondary: '#666',
  textMuted: '#999',
  textDetail: '#555',
  border: '#e0e0e0',
  borderLight: '#f0f0f0',
  chevron: '#ccc',
  primary: '#007AFF',
  primaryText: '#fff',
  onPrimaryText: '#007AFF',
  success: '#4CAF50',
  error: '#f44336',
  warning: '#FF9500',
  classSundaySchool: '#007AFF',
  classSmallGroup: '#5856D6',
  classFNA: '#FF9500',
  classBibleStudy: '#34C759',
  alertWarningBg: '#FFF8E1',
  alertWarningBorder: '#FFE082',
  alertInfoBg: '#E3F2FD',
  alertInfoBorder: '#90CAF9',
  alertSuccessBg: '#E8F5E9',
  alertSuccessText: '#2E7D32',
  alertDangerBg: '#FFEBEE',
  alertDangerText: '#C62828',
  alertOrangeBg: '#FFF3E0',
  alertOrangeText: '#E65100',
  tabBarBackground: '#fff',
  tabBarActiveTint: '#007AFF',
  tabBarInactiveTint: '#999',
  tabBarBorder: '#e0e0e0',
}

export const darkColors: ThemeColors = {
  background: '#121212',
  card: '#1E1E1E',
  inputBackground: '#2C2C2C',
  textPrimary: '#E0E0E0',
  textSecondary: '#9E9E9E',
  textMuted: '#757575',
  textDetail: '#BDBDBD',
  border: '#333333',
  borderLight: '#2C2C2C',
  chevron: '#666666',
  primary: '#007AFF',
  primaryText: '#fff',
  onPrimaryText: '#4DA3FF',
  success: '#66BB6A',
  error: '#EF5350',
  warning: '#FFA726',
  classSundaySchool: '#4DA3FF',
  classSmallGroup: '#7B79E5',
  classFNA: '#FFA726',
  classBibleStudy: '#5AD67D',
  alertWarningBg: '#3E3518',
  alertWarningBorder: '#5C4F1A',
  alertInfoBg: '#152638',
  alertInfoBorder: '#1D3A5C',
  alertSuccessBg: '#1A2E1B',
  alertSuccessText: '#66BB6A',
  alertDangerBg: '#2E1516',
  alertDangerText: '#EF5350',
  alertOrangeBg: '#2E2010',
  alertOrangeText: '#FFA726',
  tabBarBackground: '#1E1E1E',
  tabBarActiveTint: '#4DA3FF',
  tabBarInactiveTint: '#757575',
  tabBarBorder: '#333333',
}
